name: format

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - uses: actions/checkout@v2
      - name: install dotnet-format
        # use development builds from azure for proper .NET 5 support
        run: dotnet tool install -g dotnet-format --version 5.0.152601 --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
      - name: Format code
        run: |
          dotnet format
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff-index --quiet HEAD || { echo 'Please format your code using dotnet-format. See https://github.com/dotnet/format#installing-development-builds'; exit 1; }
